### ISSUE TITLE
Image doesnt load 

### ISSUE THREAD

**Issue by Robosid** [eholk/PlenopticJS#1]
Hi Eric, 
Image isn't loaded on opening index.html. Please guide me through the process of making your code work on my computer. Really sleek and well written code, i must say. its just that, i'm not able to make it work on my system. Any help would be appreciated.

Cheers,
Sid

**Comment by eholk** [comment]
I just noticed you closed this a while ago. Were you able to get it working? I've noticed loading the image can be flaky on different browser/device combinations, but I haven't really looked into why.
